apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: ${DB_NAME}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: false
    isDefault: true
    editable: true
